import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppLayout from "@/components/layout/AppLayout";
import Logo from "@/components/navigation/Logo";
import { ExternalLink } from "lucide-react";
import Footer from "@/components/navigation/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My UI Refrence Guide",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} scrolly`}>
        <AppLayout />
        <div className="flex flex-col min-h-screen mt-10">
          <main className="flex flex-col items-center px-1">{children}</main>
          <div className="flex-grow"></div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
