import CodePreview from "@/components/_cards/CodePreview";
import Header from "@/components/_layout/Header";
import { DefaultBar, NavLike } from "@/components/Page/TopBarEx";

function TopBarPage() {
  return (
    <>
      <CodePreview title="Header.tsx" code={header}>
        <div className="w-full h-60 border">
          <Header className="border-b">
            <div className="font-mono text-xl w-full text-center">Top Bar</div>
          </Header>
        </div>
      </CodePreview>
      <CodePreview title="ExampleBar.tx" code={ex}>
        <DefaultBar />
      </CodePreview>
      <CodePreview title="NavLayout.tsx" code={navlayout}>
        <NavLike />
      </CodePreview>
      <CodePreview title="@layout.tsx" code={layouttsx}>
        <NavLike />
      </CodePreview>
    </>
  );
}
export default TopBarPage;

const header = `
interface HeaderProps {
  className?: string;
  children: React.ReactNode;
}
export default function Header(props: HeaderProps) {
  return (
    <header
      className={\`fixed flex gap-1 w-full min-h-fit items-center top-0 left-0 \${props.className}\`}
    >
      {props.children}
    </header>
  );
}
`;
const navlayout = `
import { SessionBar, DefaultBar } from "./TopBar";
import { cookies } from "next/headers";

export default async function NavLayout() {
  const hasSession = cookies().has("session");
  const cookie = cookies().get("session");
  console.log(cookie);
  if (hasSession) {
    return <SessionBar />;
  } else {
    return <DefaultBar />;
  }
}
`;
const layouttsx = `
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavLayout from "@/components/Nav/NavLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavLayout />
        {children}
      </body>
    </html>
  );
}
`;

const ex = `
"use client";

import Header from "./Header";
import Link from "next/link";
import Image from "next/image";
import { usePathname } from "next/navigation";

function Logo() {
  return (
    <Link href="/">
      <Image
        src="/vercel.svg"
        alt="Vercel Logo"
        className="dark:invert"
        width={100}
        height={24}
        priority
      />
    </Link>
  );
}

export function DefaultBar() {
  const pathname = usePathname();

  return (
    <Header className="bg-inherit shadow-2xl px-2">
      <Logo />
      <div className="flex-grow"></div>
      {pathname != "/login" && (
        <Link href={"/login"}>
          <div className="border rounded py-1 px-2 cursor-pointer">Log in</div>
        </Link>
      )}
      {pathname != "/signup" && (
        <Link href={"/signup"}>
          <div className="w-0  overflow-hidden md:w-full  md:border md:rounded md:py-1 md:px-2 md:cursor-pointer">
            Sign up
          </div>
        </Link>
      )}
    </Header>
  );
}
`;
